apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: vsphere-sno-vzocp
  namespace: openshift-gitops
spec:
  ignoreDifferences:
    - group: hive.openshift.io
      jsonPointers:
        - /spec/installed
      kind: ClusterDeployment
    - group: hive.openshift.io
      jsonPointers:
        - /spec
      kind: ClusterDeployment
    - group: extensions.hive.openshift.io
      jsonPointers:
        - /spec
      kind: AgentClusterInstall
    - kind: Secret
      jsonPointers:
        - /data/host
        - /data/token
        - /data/vcenter_validate_ssl
        - /data/vcenter_fqdn
        - /data/vcenter_username
        - /data/vcenter_password
        - /data/.dockerconfigjson
        - /data
    - kind: Secret
      group: core
      jsonPointers:
        - /data/host
        - /data/token
        - /data/vcenter_validate_ssl
        - /data/vcenter_fqdn
        - /data/vcenter_username
        - /data/vcenter_password
        - /data/.dockerconfigjson
        - /data
    - kind: Secret
      group: v1
      jsonPointers:
        - /data/host
        - /data/token
        - /data/vcenter_validate_ssl
        - /data/vcenter_fqdn
        - /data/vcenter_username
        - /data/vcenter_password
        - /data/.dockerconfigjson
        - /data
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/xphyr/vsphere_ztp_demo.git'
    targetRevision: HEAD
    ## Path is the repo directory that containers the cluster(s) configuration and deployment manifests
    path: ztp-clusters/vsphere/sno/vzocp
    #path: ztp-clusters/${INFRA}/${DEPLOYMENT_TYPE}/${CLUSTER_NAME}
    ## Enable recursive sub-directory search to enable management of multiple cluster from this single Application
    directory:
      recurse: true
  project: ztp-clusters
  syncPolicy: {}