---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: vzocp
  namespace: vzocp
  labels:
    name: vzocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: Home
    cluster: Lab
    cluster-name: vzocp
    cluster-domain: vzocp.xphyrlab.net
    cluster-role: ztp-spoke
    #cluster.open-cluster-management.io/clusterset: default
spec:
  hubAcceptsClient: true
