---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: vzocp-vsphere-bootstrap
  namespace: vzocp
  labels:
    name: vzocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: Home
    cluster: Lab
    cluster-name: vzocp
    cluster-domain: vzocp.xphyrlab.net
    cluster-role: ztp-spoke
spec:
  tower_auth_secret: ansible-tower-credentials
  job_template_name: create-vsphere-infra-ztp
  extra_vars:
    vcenter_credentials_secret_namespace: vzocp
    vcenter_credentials_secret_name: xphyrlab-vcenter-credentials

    infraenv_namespace: vzocp
    infraenv_name: vzocp

    cluster_configmap_namespace: vzocp
    cluster_configmap_name: vzocp-cluster-config
