---
apiVersion: v1
kind: Secret
metadata:
  name: ztp-ssh-key
  namespace: vsphere-ocpha
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "ztp-credentials/ztp-ssh-key"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: '.*'
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
  labels:
    name: vsphere-ocpha
    cloud: vSphere
    vendor: OpenShift
    datacenter: Home
    cluster: Lab
    cluster-name: vsphere-ocpha
    cluster-domain: vsphere-ocpha.xphyrlab.net
    cluster-role: ztp-spoke