---
apiVersion: v1
kind: Secret
metadata:
  name: xphyrlab-vcenter-credentials
  namespace: vzocp
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "ztp-credentials/xphyrlab-vcenter-credentials"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: '.*'
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
  labels:
    name: vzocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: Home
    cluster: Lab
    cluster-name: vzocp
    cluster-domain: vzocp.xphyrlab.net
    cluster-role: ztp-spoke