---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: sno-ocp
  namespace: sno-ocp
  annotations:
    agent-install.openshift.io/install-config-overrides: '{"platform": {"type": "vsphere"}}'
    #agent-install.openshift.io/install-config-overrides: '{"platform":{"type":"vsphere"}}'
  labels:
    name: sno-ocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: Home
    cluster: Lab
    cluster-name: sno-ocp
    cluster-domain: sno-ocp.xphyrlab.net
    cluster-role: ztp-spoke
spec:
  clusterDeploymentRef:
    name: sno-ocp
  imageSetRef:
    name: openshift-v4.10.3
  holdInstallation: false
  networking:
    networkType: OVNKubernetes
    #userManagedNetworking: false
    clusterNetwork:
      - cidr: "10.128.0.0/14"
        hostPrefix: 23
    serviceNetwork:
      - "172.30.0.0/16"
    machineNetwork:
      - cidr: "172.16.25.0/24"
  provisionRequirements:
    controlPlaneAgents: 1
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCeld/J2xb2enje/rCx6LdRIoutB+V5pcqJqqMGF0MMjdskFaAdVl9WqNf1j/waHUcT/gGut3XfgiyFZ4uZJRbYWrWms5RtLx9Wt5UFAa1kHpkU6m00M3mPBXxd/cTml6gYbbQmfv7S5XyAofVNgeTJbmxAu1dACcTt02GA5Xb4SvkktSiAsFr3Kfq4fVOstut/AWOZPAa0SiNXo+SkKI+HuyaHwLvwiQI/hqhpgZW7liYoDCOtt1Lhn3l8sRoZNsLINDPL35KUWz1z74/zJLxFKydeTmiq56NI3O56BOg0WZYfsxKQtvkN0JpcXvu59+MpoCAQbeInUScvRaMsBk3bn4IXyjRkkc9YoYY9Fefb/p/6xiPY2/aZzNB2U0PmZLJMr12zRFb4eUiybrbEbS+4KUnIVOGTY5/223FlkqTCdJXNOke9RdSpIuPT9YzX+KNjv3HOi6Z+emDd95c84HrhtSYOOlnGRA/lDoRrsy4SBdIo7CTyvyiRAr3AM68wxP0IjpEYDgnvi8vskb9kW/L38KieqkG8dObZb/W4aSIhy/1nr6qvyyqfQ9leTUhCZE5M41htS2chnIKvHyRHbcaTVEcmn9yTOYVqdpQwwDht+LOivyxRl/mrPZJxOfKV9hxPvKq7G2SpsqYBSCxAfOg1YLUvwFG65jCaPCfiz1HH9w=="
