---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: sno-ocp
  namespace: sno-ocp
  labels:
    name: sno-ocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: Home
    cluster: Lab
    cluster-name: sno-ocp
    cluster-domain: sno-ocp.xphyrlab.net
    cluster-role: ztp-spoke
spec:
  clusterName: sno-ocp
  clusterNamespace: sno-ocp
  clusterLabels:
    name: sno-ocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: Home
    cluster: Lab
    cluster-name: sno-ocp
    cluster-domain: sno-ocp.xphyrlab.net
    cluster-role: ztp-spoke
    #cluster.open-cluster-management.io/clusterset: default
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  #workManager:
  #  enabled: true
