---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: sno-ocp
  namespace: sno-ocp
  labels:
    name: sno-ocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: Home
    cluster: Lab
    cluster-name: sno-ocp
    cluster-domain: sno-ocp.xphyrlab.net
    cluster-role: ztp-spoke
    autoupgrade: true
    #cluster.open-cluster-management.io/clusterset: default
spec:
  hubAcceptsClient: true
