---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: sno-ocp
  namespace: sno-ocp
  labels:
    name: sno-ocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: Home
    cluster: Lab
    cluster-name: sno-ocp
    cluster-domain: sno-ocp.xphyrlab.net
    cluster-role: ztp-spoke
    agentclusterinstalls.extensions.hive.openshift.io/location: loe-rdu
    networkType: static
spec:
  agentLabels:
    agentclusterinstalls.extensions.hive.openshift.io/location: loe-rdu
    agentBareMetal-generated-infraenv-ai-flow: sno-ocp
  clusterRef:
    name: sno-ocp
    namespace: sno-ocp
  sshAuthorizedKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCeld/J2xb2enje/rCx6LdRIoutB+V5pcqJqqMGF0MMjdskFaAdVl9WqNf1j/waHUcT/gGut3XfgiyFZ4uZJRbYWrWms5RtLx9Wt5UFAa1kHpkU6m00M3mPBXxd/cTml6gYbbQmfv7S5XyAofVNgeTJbmxAu1dACcTt02GA5Xb4SvkktSiAsFr3Kfq4fVOstut/AWOZPAa0SiNXo+SkKI+HuyaHwLvwiQI/hqhpgZW7liYoDCOtt1Lhn3l8sRoZNsLINDPL35KUWz1z74/zJLxFKydeTmiq56NI3O56BOg0WZYfsxKQtvkN0JpcXvu59+MpoCAQbeInUScvRaMsBk3bn4IXyjRkkc9YoYY9Fefb/p/6xiPY2/aZzNB2U0PmZLJMr12zRFb4eUiybrbEbS+4KUnIVOGTY5/223FlkqTCdJXNOke9RdSpIuPT9YzX+KNjv3HOi6Z+emDd95c84HrhtSYOOlnGRA/lDoRrsy4SBdIo7CTyvyiRAr3AM68wxP0IjpEYDgnvi8vskb9kW/L38KieqkG8dObZb/W4aSIhy/1nr6qvyyqfQ9leTUhCZE5M41htS2chnIKvHyRHbcaTVEcmn9yTOYVqdpQwwDht+LOivyxRl/mrPZJxOfKV9hxPvKq7G2SpsqYBSCxAfOg1YLUvwFG65jCaPCfiz1HH9w=="
  pullSecretRef:
    name: ztp-deployment-pull-secret
  #ignitionConfigOverride: '{"ignition": {"version": "3.1.0"}, "storage": {"files": [{"path": "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem", "overwrite": true, "contents": {"source": "data:text/plain;base64,root_ca_bundle_pem_in_base64"} } ] } }'
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: sno-ocp
